version: '2'
services:
    workinghours-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/workinghours/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=workinghours
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
